name: Typecheck Agda

on:
  push:
    branches: [ "trunk" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Agda
        uses: agda/agda-setup-action@v1
        with:
          agda-version: '2.8.0'

      - name: Install Cubical
        run: |
          git clone --depth 1 --branch v0.9 https://github.com/agda/cubical.git ~/.agda/cubical
          mkdir -p ~/.agda
          echo "$HOME/.agda/cubical/cubical.agda-lib" > ~/.config/agda/libraries

      - name: Typecheck project
        run: make
